import React from "react";
import CardPage from "/src/Components/CardPage";
import { FaQuestion } from "react-icons/fa";

function Strangers() {
  return (
    <div>
      <CardPage
        packname="Strangers"
        prompts={[
          "What's something that brings you joy?",
          "If you could live anywhere in the world, where would it be and why?",
          "What's a hobby or interest you're passionate about?",
          "What's a skill or talent you have that not many people know about?",
          "What's a book or movie that has had a big impact on you?",
          "What's a place you've traveled to that left a lasting impression on you?",
          "What's a goal you have for the next year, and how are you working towards it?",
          "What's a cause or issue you feel strongly about, and why?",
          "What's a memorable experience you've had recently?",
          "What's a tradition or ritual from your culture or background that you cherish?",
          "What's one thing you're grateful for today?",
          "What's a decision you've made that you're proud of?",
          "What's a lesson you've learned from a mistake or failure?",
          "What's a skill or talent you'd like to develop or improve?",
          "What's a question you've been pondering lately?",
          "What's one change you'd like to see in your community?",
          "What's a piece of advice that has stuck with you?",
          "What's a small act of kindness you've experienced that meant a lot to you?",
          "What's something you enjoy doing on weekends or in your free time?",
          "What's a place in your city or town you think everyone should visit?",
          "What's a recent accomplishment you're proud of?",
          "What's something you find challenging about your current job or studies?",
          "What's a skill or knowledge you'd like to share with others?",
          "What's a memorable meal you've had recently, and where was it?",
          "What's a talent you have that not many people know about?",
          "What's a story from your childhood that always makes you smile?",
          "What's a movie or TV show you've watched recently that you enjoyed?",
          "What's a dream or aspiration you've had since you were young?",
          "What's something you'd like to learn more about?",
          "What's a memorable concert or event you've attended?",
          "What's a place you've always wanted to visit?",
          "What's a favorite holiday or celebration of yours, and how do you typically celebrate it?",
          "What's a skill or talent you'd like to acquire in the future?",
          "What's a topic you enjoy discussing or learning about?",
          "What's a project or hobby you're currently working on?",
          "What's a cause or charity you support, and why is it important to you?",
          "What's a quality you admire in others and strive to cultivate yourself?",
          "What's a new hobby or interest you've recently picked up?",
          "What's a historical event or period you find fascinating?",
          "What's a favorite book or author of yours, and why do you recommend it?",
          "What's a skill or activity you'd like to try but haven't yet?",
          "What's a piece of advice you'd give to your younger self?",
          "What's a challenge you've faced recently, and how did you overcome it?",
          "What's a topic or issue you think more people should be aware of?",
          "What's a skill or talent you'd like to share with others?",
          "What's a piece of wisdom or philosophy that guides your life?",
          "What's a favorite dish or food from your culture or background?",
          "What's a place in your city or town that holds special meaning for you?",
          "What's a decision you've made that led to a positive change in your life?",
          "What's a goal you've achieved that you're proud of?",
          "What's a hobby or interest you're passionate about?",
          "What's a dream vacation you've always wanted to take?",
          "What's a project you're currently working on that excites you?",
          "What's a cause or charity you care deeply about?",
          "What's a skill or talent you've developed over the years?",
          "What's a book or movie that has influenced your perspective on life?",
          "What's a place you've visited that left a lasting impression on you?",
          "What's a memorable experience you've had recently?",
          "What's a lesson you've learned from a difficult situation?",
          "What's a tradition or ritual from your culture or background that you cherish?",
          "What's one thing you're grateful for today?",
          "What's a decision you've made that you're proud of?",
          "What's a lesson you've learned from a mistake or failure?",
          "What's a skill or talent you'd like to develop further?",
          "What's a question you've been pondering lately?",
          "What's one change you'd like to see in your community?",
          "What's a piece of advice that has stuck with you?",
          "What's a small act of kindness you've experienced that meant a lot to you?",
          "What's something you enjoy doing on weekends or in your free time?",
          "What's a place in your city or town you think everyone should visit?",
          "What's a recent accomplishment you're proud of?",
          "What's something you find challenging about your current job or studies?",
          "What's a skill or knowledge you'd like to share with others?",
          "What's a memorable meal you've had recently, and where was it?",
          "What's a talent you have that not many people know about?",
          "What's a story from your childhood that always makes you smile?",
          "What's a movie or TV show you've watched recently that you enjoyed?",
          "What's a dream or aspiration you've had since you were young?",
          "What's something you'd like to learn more about?",
          "What's a memorable concert or event you've attended?",
          "What's a place you've always wanted to visit?",
          "What's a favorite holiday or celebration of yours, and how do you typically celebrate it?",
          "What's a skill or talent you'd like to acquire in the future?",
          "What's a topic you enjoy discussing or learning about?",
          "What's a project or hobby you're currently working on?",
          "What's a cause or charity you support, and why is it important to you?",
          "What's a quality you admire in others and strive to cultivate yourself?",
          "What's a new hobby or interest you've recently picked up?",
          "What's a historical event or period you find fascinating?",
          "What's a favorite book or author of yours, and why do you recommend it?",
          "What's a skill or activity you'd like to try but haven't yet?",
          "What's a piece of advice you'd give to your younger self?",
          "What's a challenge you've faced recently, and how did you overcome it?",
          "What's a topic or issue you think more people should be aware of?",
          "What's a skill or talent you'd like to share with others?",
          "What's a piece of wisdom or philosophy that guides your life?",
          "What's a favorite dish or food from your culture or background?",
          "What's a place in your city or town that holds special meaning for you?",
          "What's a decision you've made that led to a positive change in your life?",
          "What's a goal you've achieved that you're proud of?",
        ]}
      />
    </div>
  );
}

export default Strangers;
